require('settings/telescope')
require('settings/autosave')
require('settings/neogit')
require('settings/treesitter')
require('settings/lualine')
require('settings/cmp')
require('settings/substitute')
require('settings/dial')
require('settings/comment')
require('settings/yabs')
require('settings/camelcase')
require('settings/bqf')
require('settings/dressing')
require('settings/debug')

-- set up vim notify
vim.notify = require('notify')
